/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BecomeAdvertiserRouteImport } from './routes/become-advertiser'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertiserTrendsRouteImport } from './routes/advertiser.trends'
import { Route as AdvertiserActivityRouteImport } from './routes/advertiser.activity'
import { Route as AdminStatusRouteImport } from './routes/admin.status'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdIdRouteImport } from './routes/ad.$id'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedOnboardingInterestsRouteImport } from './routes/_authenticated/onboarding.interests'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardPaymentResultRouteImport } from './routes/_authenticated/dashboard/payment-result'
import { Route as AuthenticatedDashboardNewAdRouteImport } from './routes/_authenticated/dashboard/new-ad'
import { Route as AuthenticatedDashboardEditAdIdRouteImport } from './routes/_authenticated/dashboard/edit-ad.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAdvertiserRoute = BecomeAdvertiserRouteImport.update({
  id: '/become-advertiser',
  path: '/become-advertiser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserTrendsRoute = AdvertiserTrendsRouteImport.update({
  id: '/advertiser/trends',
  path: '/advertiser/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserActivityRoute = AdvertiserActivityRouteImport.update({
  id: '/advertiser/activity',
  path: '/advertiser/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusRoute = AdminStatusRouteImport.update({
  id: '/admin/status',
  path: '/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdRoute = AdIdRouteImport.update({
  id: '/ad/$id',
  path: '/ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingInterestsRoute =
  AuthenticatedOnboardingInterestsRouteImport.update({
    id: '/onboarding/interests',
    path: '/onboarding/interests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPaymentResultRoute =
  AuthenticatedDashboardPaymentResultRouteImport.update({
    id: '/dashboard/payment-result',
    path: '/dashboard/payment-result',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNewAdRoute =
  AuthenticatedDashboardNewAdRouteImport.update({
    id: '/dashboard/new-ad',
    path: '/dashboard/new-ad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEditAdIdRoute =
  AuthenticatedDashboardEditAdIdRouteImport.update({
    id: '/dashboard/edit-ad/$id',
    path: '/dashboard/edit-ad/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-advertiser': typeof BecomeAdvertiserRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/ad/$id': typeof AdIdRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/status': typeof AdminStatusRoute
  '/advertiser/activity': typeof AdvertiserActivityRoute
  '/advertiser/trends': typeof AdvertiserTrendsRoute
  '/dashboard/new-ad': typeof AuthenticatedDashboardNewAdRoute
  '/dashboard/payment-result': typeof AuthenticatedDashboardPaymentResultRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/onboarding/interests': typeof AuthenticatedOnboardingInterestsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/edit-ad/$id': typeof AuthenticatedDashboardEditAdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-advertiser': typeof BecomeAdvertiserRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/ad/$id': typeof AdIdRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/status': typeof AdminStatusRoute
  '/advertiser/activity': typeof AdvertiserActivityRoute
  '/advertiser/trends': typeof AdvertiserTrendsRoute
  '/dashboard/new-ad': typeof AuthenticatedDashboardNewAdRoute
  '/dashboard/payment-result': typeof AuthenticatedDashboardPaymentResultRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/onboarding/interests': typeof AuthenticatedOnboardingInterestsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/edit-ad/$id': typeof AuthenticatedDashboardEditAdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-advertiser': typeof BecomeAdvertiserRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/ad/$id': typeof AdIdRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/status': typeof AdminStatusRoute
  '/advertiser/activity': typeof AdvertiserActivityRoute
  '/advertiser/trends': typeof AdvertiserTrendsRoute
  '/_authenticated/dashboard/new-ad': typeof AuthenticatedDashboardNewAdRoute
  '/_authenticated/dashboard/payment-result': typeof AuthenticatedDashboardPaymentResultRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/onboarding/interests': typeof AuthenticatedOnboardingInterestsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/edit-ad/$id': typeof AuthenticatedDashboardEditAdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/become-advertiser'
    | '/browse'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin'
    | '/me'
    | '/ad/$id'
    | '/admin/approvals'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/status'
    | '/advertiser/activity'
    | '/advertiser/trends'
    | '/dashboard/new-ad'
    | '/dashboard/payment-result'
    | '/dashboard/profile'
    | '/onboarding/interests'
    | '/dashboard/'
    | '/dashboard/edit-ad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/become-advertiser'
    | '/browse'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin'
    | '/me'
    | '/ad/$id'
    | '/admin/approvals'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/status'
    | '/advertiser/activity'
    | '/advertiser/trends'
    | '/dashboard/new-ad'
    | '/dashboard/payment-result'
    | '/dashboard/profile'
    | '/onboarding/interests'
    | '/dashboard'
    | '/dashboard/edit-ad/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/become-advertiser'
    | '/browse'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/ad/$id'
    | '/admin/approvals'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/status'
    | '/advertiser/activity'
    | '/advertiser/trends'
    | '/_authenticated/dashboard/new-ad'
    | '/_authenticated/dashboard/payment-result'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/onboarding/interests'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/edit-ad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BecomeAdvertiserRoute: typeof BecomeAdvertiserRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdIdRoute: typeof AdIdRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminStatusRoute: typeof AdminStatusRoute
  AdvertiserActivityRoute: typeof AdvertiserActivityRoute
  AdvertiserTrendsRoute: typeof AdvertiserTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-advertiser': {
      id: '/become-advertiser'
      path: '/become-advertiser'
      fullPath: '/become-advertiser'
      preLoaderRoute: typeof BecomeAdvertiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/trends': {
      id: '/advertiser/trends'
      path: '/advertiser/trends'
      fullPath: '/advertiser/trends'
      preLoaderRoute: typeof AdvertiserTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/activity': {
      id: '/advertiser/activity'
      path: '/advertiser/activity'
      fullPath: '/advertiser/activity'
      preLoaderRoute: typeof AdvertiserActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/status': {
      id: '/admin/status'
      path: '/admin/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id': {
      id: '/ad/$id'
      path: '/ad/$id'
      fullPath: '/ad/$id'
      preLoaderRoute: typeof AdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/interests': {
      id: '/_authenticated/onboarding/interests'
      path: '/onboarding/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof AuthenticatedOnboardingInterestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/payment-result': {
      id: '/_authenticated/dashboard/payment-result'
      path: '/dashboard/payment-result'
      fullPath: '/dashboard/payment-result'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentResultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/new-ad': {
      id: '/_authenticated/dashboard/new-ad'
      path: '/dashboard/new-ad'
      fullPath: '/dashboard/new-ad'
      preLoaderRoute: typeof AuthenticatedDashboardNewAdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/edit-ad/$id': {
      id: '/_authenticated/dashboard/edit-ad/$id'
      path: '/dashboard/edit-ad/$id'
      fullPath: '/dashboard/edit-ad/$id'
      preLoaderRoute: typeof AuthenticatedDashboardEditAdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedDashboardNewAdRoute: typeof AuthenticatedDashboardNewAdRoute
  AuthenticatedDashboardPaymentResultRoute: typeof AuthenticatedDashboardPaymentResultRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedOnboardingInterestsRoute: typeof AuthenticatedOnboardingInterestsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardEditAdIdRoute: typeof AuthenticatedDashboardEditAdIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedDashboardNewAdRoute: AuthenticatedDashboardNewAdRoute,
  AuthenticatedDashboardPaymentResultRoute:
    AuthenticatedDashboardPaymentResultRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedOnboardingInterestsRoute: AuthenticatedOnboardingInterestsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardEditAdIdRoute: AuthenticatedDashboardEditAdIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BecomeAdvertiserRoute: BecomeAdvertiserRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdIdRoute: AdIdRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminStatusRoute: AdminStatusRoute,
  AdvertiserActivityRoute: AdvertiserActivityRoute,
  AdvertiserTrendsRoute: AdvertiserTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
